apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-streaming-checkpoint
  namespace: platform-streaming
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
