apiVersion: v1
kind: Secret
metadata:
  name: iceberg-s3-secret
  namespace: platform-storage
type: Opaque
stringData:
  # MinIO credentials (same as minio-credentials secret)
  # Doi sang dedicated user khi len production
  access_key: "minioadmin"
  secret_key: "MinIO@Admin2024!"
