apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-team-TEAM_NAME
  namespace: team-TEAM_NAME
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-TEAM_NAME-reader
  namespace: team-TEAM_NAME