gitea:
  admin:
    username: gitea-admin
    password: "Gitea@Admin2024!"
    email: "admin@platform.internal"
  config:
    app:
      APP_NAME: "Platform Gitea"
    server:
      DOMAIN: gitea-http.platform-ops
      ROOT_URL: http://gitea-http.platform-ops:3000
      LOCAL_ROOT_URL: http://gitea-http.platform-ops:3000
      SSH_DOMAIN: 100.87.165.70
    repository:
      DEFAULT_BRANCH: main
      DEFAULT_PRIVATE: true
      MAX_CREATION_LIMIT: -1
    service:
      DISABLE_REGISTRATION: true
      REQUIRE_SIGNIN_VIEW: true
    webhook:
      ALLOWED_HOST_LIST: "*"
      SKIP_TLS_VERIFY: true
    actions:
      ENABLED: true
    cache:
      ADAPTER: memory
    session:
      PROVIDER: memory
    queue:
      TYPE: level

service:
  http:
    type: NodePort
    port: 3000
    nodePort: 30300
  ssh:
    type: ClusterIP
    port: 22

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 512Mi

persistence:
  enabled: true
  storageClass: local-path
  size: 5Gi                        # Dev: 5Gi (prod: 50Gi)

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: latest
  persistence:
    storageClass: local-path
    size: 2Gi                      # Dev: 2Gi (prod: 20Gi)
  auth:
    password: "Gitea@PG2024!"

postgresql-ha:
  enabled: false

redis-cluster:
  enabled: false
redis:
  enabled: false

valkey-cluster:
  enabled: false
valkey:
  enabled: false