apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KaitoKid-123/platform-infra
    targetRevision: main
    path: services/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-storage
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true