apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-data
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KaitoKid-123/platform-infra
    targetRevision: main
    path: services/data
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true